<?php

use Illuminate\Database\Seeder;
use App\Client;
class ClientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $clients = array(
		  array('cl_code' => '281','cl_name' => '28one'),
		  array('cl_code' => 'aero','cl_name' => 'Aerolatte'),
		  array('cl_code' => 'ahac','cl_name' => 'AHAC d.o.o.'),
		  array('cl_code' => 'aiv','cl_name' => 'AIV'),
		  array('cl_code' => 'aiv','cl_name' => 'AIV'),
		  array('cl_code' => 'af','cl_name' => 'Agua Fun'),
		  array('cl_code' => 'ageo','cl_name' => 'Ageo'),
		  array('cl_code' => 'agn','cl_name' => 'Agniezka'),
		  array('cl_code' => 'al','cl_name' => 'Anlinternational'),
		  array('cl_code' => 'am','cl_name' => 'Bravus'),
		  array('cl_code' => 'ass','cl_name' => 'Assman'),
		  array('cl_code' => 'ax','cl_name' => 'Aquaparx'),
		  array('cl_code' => 'b2b','cl_name' => 'B2B'),
		  array('cl_code' => 'ba','cl_name' => 'Bash-tech Gmbh'),
		  array('cl_code' => 'bb','cl_name' => 'Bella'),
		  array('cl_code' => 'so','cl_name' => 'Sosaga'),
		  array('cl_code' => 'bd','cl_name' => 'BlueUmbrella'),
		  array('cl_code' => 'om','cl_name' => 'Overmax'),
		  array('cl_code' => 'bl','cl_name' => 'Blessland'),
		  array('cl_code' => 'bm','cl_name' => 'BIMIX'),
		  array('cl_code' => 'bp','cl_name' => 'Buildpro'),
		  array('cl_code' => 'bv','cl_name' => 'Beyond Vintage'),
		  array('cl_code' => 'ca','cl_name' => 'C&A'),
		  array('cl_code' => 'ccm','cl_name' => 'Creative Concepts'),
		  array('cl_code' => 'cd','cl_name' => 'Ceing'),
		  array('cl_code' => 'ce','cl_name' => 'CE China'),
		  array('cl_code' => 'cf','cl_name' => 'Clever-Filter'),
		  array('cl_code' => 'cic','cl_name' => 'C.I.Castro & Co.'),
		  array('cl_code' => 'como','cl_name' => 'Como International'),
		  array('cl_code' => 'cy','cl_name' => 'Chayon'),
		  array('cl_code' => 'dr','cl_name' => 'Dom Reklamy'),
		  array('cl_code' => 'dyg','cl_name' => 'DYG'),
		  array('cl_code' => 'ebim','cl_name' => 'Ebim'),
		  array('cl_code' => 'ee','cl_name' => 'Euro Expasion'),
		  array('cl_code' => 'ef','cl_name' => 'Effire'),
		  array('cl_code' => 'emb','cl_name' => 'Emberton'),
		  array('cl_code' => 'fd','cl_name' => 'Fusion Dynamics'),
		  array('cl_code' => 'fs','cl_name' => 'First stuff'),
		  array('cl_code' => 'gcn','cl_name' => 'GCN Turk'),
		  array('cl_code' => 'gem','cl_name' => 'Gemini'),
		  array('cl_code' => 'gev','cl_name' => 'GEV'),
		  array('cl_code' => 'gg','cl_name' => 'Geiger Werbemittel GmbH'),
		  array('cl_code' => 'ghc','cl_name' => 'GHC'),
		  array('cl_code' => 'gm','cl_name' => 'Goldmaster'),
		  array('cl_code' => 'go','cl_name' => 'Golze'),
		  array('cl_code' => 'grh','cl_name' => 'Gloria Haus'),
		  array('cl_code' => 'gz','cl_name' => 'Ground-Zero'),
		  array('cl_code' => 'ha','cl_name' => 'Hama'),
		  array('cl_code' => 'he','cl_name' => 'Hafele'),
		  array('cl_code' => 'heim','cl_name' => 'Heim'),
		  array('cl_code' => 'idp','cl_name' => 'Ideo Plastics Inc.'),
		  array('cl_code' => 'if','cl_name' => 'Inflate Design'),
		  array('cl_code' => 'imi','cl_name' => 'IMI Partner'),
		  array('cl_code' => 'ing','cl_name' => 'Ingplan'),
		  array('cl_code' => 'io','cl_name' => 'I-onik'),
		  array('cl_code' => 'is','cl_name' => 'Instylo'),
		  array('cl_code' => 'its','cl_name' => 'Intersold'),
		  array('cl_code' => 'itm','cl_name' => 'Intermarket'),
		  array('cl_code' => 'fta','cl_name' => 'FTA'),
		  array('cl_code' => 'iv','cl_name' => 'Inverto'),
		  array('cl_code' => 'jfc','cl_name' => 'JFC'),
		  array('cl_code' => 'jmg','cl_name' => 'JM Global Sourcing'),
		  array('cl_code' => 'kb','cl_name' => 'Kobil'),
		  array('cl_code' => 'kfb','cl_name' => 'KFB'),
		  array('cl_code' => 'ko','cl_name' => 'Keyos'),
		  array('cl_code' => 'lkg','cl_name' => 'LKG'),
		  array('cl_code' => 'lpw','cl_name' => 'Looptworks'),
		  array('cl_code' => 'lt','cl_name' => 'Lloytron'),
		  array('cl_code' => 'Ltg','cl_name' => 'Link Together'),
		  array('cl_code' => 'lx','cl_name' => 'Laltex'),
		  array('cl_code' => 'mdh','cl_name' => 'MDH'),
		  array('cl_code' => 'mms','cl_name' => 'MMS'),
		  array('cl_code' => 'my','cl_name' => 'Meyra'),
		  array('cl_code' => 'na','cl_name' => 'North American'),
		  array('cl_code' => 'nex','cl_name' => 'Nexus'),
		  array('cl_code' => 'ni','cl_name' => 'Niposom'),
		  array('cl_code' => 'nor','cl_name' => 'Nordic'),
		  array('cl_code' => 'not','cl_name' => 'Notio'),
		  array('cl_code' => 'np','cl_name' => 'Northpeak'),
		  array('cl_code' => 'og','cl_name' => 'Original Grain'),
		  array('cl_code' => 'op','cl_name' => 'Opitec'),
		  array('cl_code' => 'os','cl_name' => 'Out-source'),
		  array('cl_code' => 'osg','cl_name' => 'Otto Schmidt'),
		  array('cl_code' => 'pp','cl_name' => 'Primopet'),
		  array('cl_code' => 'pro','cl_name' => 'Projim'),
		  array('cl_code' => 'pr','cl_name' => 'Promotive'),
		  array('cl_code' => 'prl','cl_name' => 'Printxl'),
		  array('cl_code' => 'ps','cl_name' => 'Pritsch'),
		  array('cl_code' => 'pt','cl_name' => 'Portalux'),
		  array('cl_code' => 'pw','cl_name' => 'Payperwear'),
		  array('cl_code' => 'rdk','cl_name' => 'Rad-Kappe'),
		  array('cl_code' => 'rep','cl_name' => 'REP'),
		  array('cl_code' => 'rg','cl_name' => 'Richie-Goldies'),
		  array('cl_code' => 'rjm','cl_name' => 'RJM'),
		  array('cl_code' => 'rpc','cl_name' => 'RPC'),
		  array('cl_code' => 'rsj','cl_name' => 'RSJ'),
		  array('cl_code' => 'rtb','cl_name' => 'Retouch Brand'),
		  array('cl_code' => 'sd','cl_name' => 'Simon-Deutsch'),
		  array('cl_code' => 'sda','cl_name' => 'SDA'),
		  array('cl_code' => 'se','cl_name' => 'Seed Europte'),
		  array('cl_code' => 'scl','cl_name' => 'SCL'),
		  array('cl_code' => 'sl','cl_name' => 'Solargods'),
		  array('cl_code' => 'sms','cl_name' => 'Samson'),
		  array('cl_code' => 'sr','cl_name' => 'SERA'),
		  array('cl_code' => 'ssd','cl_name' => 'SameSame'),
		  array('cl_code' => 's-se','cl_name' => 'S-Sentials'),
		  array('cl_code' => 'st','cl_name' => 'StolComfort Gmbh.'),
		  array('cl_code' => 'te','cl_name' => 'Twine Export'),
		  array('cl_code' => 'tg','cl_name' => 'A-tech'),
		  array('cl_code' => 'tk','cl_name' => 'Trik'),
		  array('cl_code' => 'tka','cl_name' => 'Troika'),
		  array('cl_code' => 'togo','cl_name' => 'togo'),
		  array('cl_code' => 'ts','cl_name' => 'Trekstor'),
		  array('cl_code' => 'ur','cl_name' => 'Urvina'),
		  array('cl_code' => 'vbt','cl_name' => 'Vibe Technologies'),
		  array('cl_code' => 'wd','cl_name' => 'White Dragon CG Ltd'),
		  array('cl_code' => 'wr','cl_name' => 'Wealthrainbow'),
		  array('cl_code' => 'wtc','cl_name' => 'Wentronic'),
		  array('cl_code' => 'wu','cl_name' => 'Western Union Ent'),
		  array('cl_code' => 'ww','cl_name' => 'Wiwyn'),
		  array('cl_code' => 'zp','cl_name' => 'Zaomp'),
		  array('cl_code' => 'zr','cl_name' => 'Zreiss')
		);

		foreach ($clients as $key => $client) {
		 $cl[$key] = new Client();
		 $cl[$key]->client_code = $client['cl_code'];
		 $cl[$key]->client_name = $client['cl_name'];
		 $cl[$key]->save();

		}
    }
}
